# File name (including extension) is important and should be not changed.
# The reason: <https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file>

global:
  checkNewVersion: false
  sendAnonymousUsage: false

experimental:
  localPlugins:
    docker-info: # sources are located in traefik/plugins/docker-info directory
      moduleName: docker-info

serversTransport: # https://doc.traefik.io/traefik/routing/services/#serverstransport_1
  insecureSkipVerify: true

log: # https://doc.traefik.io/traefik/observability/logs/
  level: INFO # DEBUG|PANIC|FATAL|ERROR|WARN|INFO
  format: json # common|json
  
accessLog: {}

api:
  dashboard: true # enable the dashboard
  #debug: true # enable additional endpoints for debugging and profiling, served under /debug/

entryPoints:
  http:
    address: '0.0.0.0:80/tcp'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: '0.0.0.0:443/tcp'
    asDefault: true # https://github.com/traefik/traefik/pull/9100
    http3:
      advertisedPort: 443
    http:
      tls: {} # enable TLS by default for all routers
  service-only:
    address: '0.0.0.0:81/tcp' # do not expose this port outside the container
  ping:
    address: ":82"

ping: # enable the API handler `/ping` (https://doc.traefik.io/traefik/operations/ping/)
  entryPoint: ping

providers:
  file: # Docs: https://doc.traefik.io/traefik/providers/file/
    directory: /etc/traefik/dynamic # you can mount any custom config file into this directory
    watch: true
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    exposedByDefault: false

